- name: create gunicorn log file
  file:
    path: /var/opt/wsgi/tethne/logs/gunicorn_supervisor.log
    state: touch
    mode: "u=rw,g=rw,o=r"
    owner: tethne
    group: webapps
  become: yes
- name: copy gunicorn start script
  copy:
    src: files/gunicorn_start
    dest: /var/opt/wsgi/tethne/bin/gunicorn_start
    mode: "u=rwx,g=rx,o=rx"
    owner: tethne
    group: webapps
  become: yes
- name: copy supervisord configuration for tethne
  copy:
    src: files/supervisord__tethne.conf
    dest: /etc/supervisord.d/tethne.conf
    mode: "u=rw,g=r,o=r"
  become: yes
- name: reread supervisor configuration
  command: supervisorctl reread
  become: yes
- name: update supervisor with new configuration
  command: supervisorctl update
  become: yes
- name: restart tethne gunicorn process
  command: supervisorctl restart tethne
  become: yes
