- name: copy locations config for nginx
  copy:
    src: files/tethne_locations.conf
    dest: /etc/nginx/conf.d/tethne_locations.conf
  become: yes
- name: copy upstream config for nginx
  copy:
    src: files/tethne_upstream.conf
    dest: /etc/nginx/conf.d/tethne_upstream.conf
  become: yes
- name: restart nginx
  systemd:
    state: restarted
    name: nginx
  become: yes
