- name: make sure git is installed
  yum:
    name: git
    state: present
  become: yes
- name: make sure virtualenv is installed
  pip:
    name: virtualenv
    state: present
  become: yes
- name: create git repo target
  file:
    path: /var/opt/wsgi/tethne/tethne
    state: directory
    owner: tethne
    mode: "u=rwx,g=r,o=r"
    group: webapps
  become: yes
- name: get code from github
  git:
    repo: git://github.com/diging/django-tethne.git
    dest: /var/opt/wsgi/tethne/tethne
    force: yes
  become: yes
  become_user: tethne
